services:
  mongo:
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
    image: mongo
    container_name: mcp-mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./.data/mongo/data:/data/db
      - ./.data/mongo/config:/data/configdb

  agent:
    build:
      context: ./agent
      dockerfile: Dockerfile.agent
    container_name: mcp_agent
    depends_on:
      - ollama-llm
      - mongo
    environment:
      - OLLAMA_HOST=http://ollama-llm:11434
      - MONGO_URI=mongodb://admin:password@mongo:27017
      - MONGO_DB=mcp-db
    stdin_open: true
    tty: true
    volumes:
      - mcp_socket:/tmp

  agent_ui:
    build:
      context: .
      dockerfile: agent_ui/Dockerfile
    container_name: mcp_agent_ui
    ports:
      - "7860:7860"
    depends_on:
      - ollama-llm
      - mongo
    env_file:
      - ./.env
    environment:
    - OLLAMA_HOST=http://ollama-llm:11434
    - MONGO_URI=mongodb://admin:password@mongo:27017
    - MONGO_DB=mcp-db
    - GRADIO_SERVER_NAME=0.0.0.0
    - GRADIO_SERVER_PORT=7860
    - OPENAI_BASE_URL=http://ollama-llm:11434/v1
    - OPENAI_MODEL_NAME=ollama/llama3.2
    - OPENAI_API_KEY=NA

  ollama-llm:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    container_name: ollama-llm
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    pull_policy: always
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  mongo-data:
  ollama_data:
  mcp_socket: